id: I55EE7517
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:43:07.832421+00:00
last_modified: 2022-12-15 07:43:07.832456+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-008
  title: Toh_308-Questions%20Regarding%20Death%20and%20Transmigration-v2
bases:
  90C0:
    source_metadata: null
    order: 1
    base_file: 90C0.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
